spring.application.name=HrAssistance

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/kudosflow_db
spring.datasource.username=postgres
#spring.datasource.password=yourpass
spring.jpa.hibernate.ddl-auto=update

server.port=8010
#
## Ollama
#ollama.base-url=http://localhost:11434
#ollama.model=qwen2.5:14b-instruct
## File storage
#app.upload.dir=uploads/

#open router
openrouter.base-url= https://openrouter.ai/api/v1/chat/completions
openrouter.model = qwen/qwen3-235b-a22b-2507
openrouter.token = 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

# openrouter/hunter-alpha

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false