spring.application.name=HrAssistance

#database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

openrouter.base-url=${OPENROUTER_BASE_URL}
openrouter.model=${OPENROUTER_MODEL}
openrouter.token=${OPENROUTER_TOKEN}

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudflare.r2.public-domain = ${R2_PUBLIC_DOMAIN}
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.endpoint=https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com
cloudflare.r2.bucket=${R2_BUCKET_NAME}

