spring.application.name=HrAssistance

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/kudosflow_db
spring.datasource.username=postgres
#spring.datasource.password=yourpass
spring.jpa.hibernate.ddl-auto=update

server.port=8010

# Ollama
ollama.base-url=http://localhost:11434
ollama.model=llama3.2

# File storage
app.upload.dir=uploads/


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false